Dont error if one script fails

diff --git a/.chezmoiscripts/run_install-eza b/.chezmoiscripts/run_install-eza
--- a/.chezmoiscripts/run_install-eza
+++ b/.chezmoiscripts/run_install-eza
@@ -1,26 +1,31 @@
 #!/usr/bin/env zsh
 
-if command -v eza &> /dev/null; then
-    echo "Eza is already installed"
-    return
-fi
-
-ARCH=$(uname -m)
-if [ $ARCH != "x86_64" ]; then
-    echo "$ARCH is not supported"
-    return
-fi
-
-if [ "$(id -u)" -eq 0 ]; then
-    SUDO=""
-else
-    if ! command -v sudo &> /dev/null; then
-        echo "Error: sudo is not installed. Please install sudo or run as root."
-        exit 1
+function install {
+    if command -v eza &> /dev/null; then
+        echo "Eza is already installed"
+        return
     fi
-    SUDO="sudo"
-fi
 
-$SUDO zsh -c "tar -C /usr/local/bin -xzf <(curl -sL https://github.com/eza-community/eza/releases/latest/download/eza_x86_64-unknown-linux-gnu.tar.gz)"
-$SUDO chmod +x /usr/local/bin/eza
-$SUDO chown root:root /usr/local/bin/eza
+    ARCH=$(uname -m)
+    if [ $ARCH != "x86_64" ]; then
+        echo "$ARCH is not supported"
+        return
+    fi
+
+    if [ "$(id -u)" -eq 0 ]; then
+        SUDO=""
+    else
+        if ! command -v sudo &> /dev/null; then
+            echo "Error: sudo is not installed. Please install sudo or run as root."
+            exit 1
+        fi
+        SUDO="sudo"
+    fi
+
+    $SUDO zsh -c "tar -C /usr/local/bin -xzf <(curl -sL https://github.com/eza-community/eza/releases/latest/download/eza_x86_64-unknown-linux-gnu.tar.gz)"
+    $SUDO chmod +x /usr/local/bin/eza
+    $SUDO chown root:root /usr/local/bin/eza
+}
+
+install || echo Failed to install Eza
+
diff --git a/.chezmoiscripts/run_install-go b/.chezmoiscripts/run_install-go
--- a/.chezmoiscripts/run_install-go
+++ b/.chezmoiscripts/run_install-go
@@ -1,25 +1,29 @@
 #!/usr/bin/env zsh
 
-if command -v go &> /dev/null; then
-    echo "Go is already installed"
-    return
-fi
-
-ARCH=$(uname -m)
-if [ $ARCH != "x86_64" ]; then
-    echo "$ARCH is not supported"
-    return
-fi
-
-if [ "$(id -u)" -eq 0 ]; then
-    SUDO=""
-else
-    if ! command -v sudo &> /dev/null; then
-        echo "Error: sudo is not installed. Please install sudo or run as root."
-        exit 1
+function install {
+    if command -v go &> /dev/null; then
+        echo "Go is already installed"
+        return
     fi
-    SUDO="sudo"
-fi
 
-$SUDO zsh -c "tar -C /usr/local/lib -xzf <(curl -sL https://go.dev/dl/go1.21.1.linux-amd64.tar.gz)"
-$SUDO ln -s /usr/local/lib/go/bin/go /usr/local/bin/
+    ARCH=$(uname -m)
+    if [ $ARCH != "x86_64" ]; then
+        echo "$ARCH is not supported"
+        return
+    fi
+
+    if [ "$(id -u)" -eq 0 ]; then
+        SUDO=""
+    else
+        if ! command -v sudo &> /dev/null; then
+            echo "Error: sudo is not installed. Please install sudo or run as root."
+            exit 1
+        fi
+        SUDO="sudo"
+    fi
+
+    $SUDO zsh -c "tar -C /usr/local/lib -xzf <(curl -sL https://go.dev/dl/go1.21.1.linux-amd64.tar.gz)"
+    $SUDO ln -s /usr/local/lib/go/bin/go /usr/local/bin/
+}
+
+install || echo Failed to install Go
diff --git a/.chezmoiscripts/run_install-nvim b/.chezmoiscripts/run_install-nvim
--- a/.chezmoiscripts/run_install-nvim
+++ b/.chezmoiscripts/run_install-nvim
@@ -1,20 +1,25 @@
 #!/usr/bin/env zsh
 
-if command -v nvim &> /dev/null; then
-    echo "nvim is already installed"
-    return
-fi
-
-if [ "$(id -u)" -eq 0 ]; then
-    SUDO=""
-else
-    if ! command -v sudo &> /dev/null; then
-        echo "Error: sudo is not installed. Please install sudo or run as root."
-        exit 1
+function install {
+    if command -v nvim &> /dev/null; then
+        echo "nvim is already installed"
+        return
     fi
-    SUDO="sudo"
-fi
 
-$SUDO add-apt-repository -y ppa:neovim-ppa/unstable
-$SUDO apt-get update
-$SUDO apt-get install -y neovim ripgrep fd-find
+    if [ "$(id -u)" -eq 0 ]; then
+        SUDO=""
+    else
+        if ! command -v sudo &> /dev/null; then
+            echo "Error: sudo is not installed. Please install sudo or run as root."
+            exit 1
+        fi
+        SUDO="sudo"
+    fi
+
+    $SUDO add-apt-repository -y ppa:neovim-ppa/unstable
+    $SUDO apt-get update
+    $SUDO apt-get install -y neovim ripgrep fd-find
+}
+
+install || echo Failed to install nvim
+
diff --git a/.chezmoiscripts/run_onchange_apt b/.chezmoiscripts/run_onchange_apt
--- a/.chezmoiscripts/run_onchange_apt
+++ b/.chezmoiscripts/run_onchange_apt
@@ -1,14 +1,33 @@
 #!/usr/bin/env zsh
 
-if [ "$(id -u)" -eq 0 ]; then
-    SUDO=""
-else
-    if ! command -v sudo &> /dev/null; then
-        echo "Error: sudo is not installed. Please install sudo or run as root."
-        exit 1
+function install {
+    if [ "$(id -u)" -eq 0 ]; then
+        SUDO=""
+    else
+       if ! command -v sudo &> /dev/null; then
+            echo "Error: sudo is not installed. Please install sudo or run as root."
+            exit 1
+        fi
+        SUDO="sudo"
     fi
-    SUDO="sudo"
-fi
 
-$SUDO apt-get install -y unzip zip jq software-properties-common build-essential tar fzf ripgrep bat
+    $SUDO apt-get install -y \
+        bat \
+        build-essential \
+        ctop
+        fzf \
+        git \
+        jq \
+        neofetch \
+        python3-pip \
+        python3-venv \
+        ripgrep \
+        software-properties-common \
+        tar \
+        tmux \
+        unzip \
+        zip \
+}
+
+install || echo Failed to update packages
 
