Fix wezterm splits, prepare multi distro packages

diff --git a/.chezmoiscripts/run_onchange_after_00-packages.tmpl b/.chezmoiscripts/run_onchange_after_00-packages.tmpl
--- a/.chezmoiscripts/run_onchange_after_00-packages.tmpl
+++ b/.chezmoiscripts/run_onchange_after_00-packages.tmpl
@@ -1,5 +1,29 @@
 #!/usr/bin/env zsh
 
+PACKAGES=(
+    # {{ if contains .chezmoi.osRelease.idLike "debian" }}
+    #
+    # {{ else if contains .chezmoi.osRelease.idLike "rhel" }}
+    #
+    # {{ end }}
+    bat
+    btop
+    build-essential
+    direnv
+    ffmpeg
+    git
+    jq
+    neofetch
+    python3-pip
+    python3-venv
+    ripgrep
+    software-properties-common
+    tar
+    tmux
+    unzip
+    zip
+)
+
 if [ "$(id -u)" -eq 0 ]; then
     SUDO=""
 else
@@ -12,24 +36,9 @@ fi
 
 function install {
     $SUDO apt-get install -y \
-        bat \
-        btop \
-        build-essential \
-        direnv \
-        ffmpeg \
-        git \
-        jq \
-        neofetch \
-        python3-pip \
-        python3-venv \
-        ripgrep \
-        software-properties-common \
-        tar \
-        tmux \
-        unzip \
-        zip \
+        $PACKAGES \
         && \
-        echo "✅ Apt packages installed successfully"
+        echo "✅ Packages installed successfully"
     }
 
 function uninstall {
@@ -41,10 +50,10 @@ function uninstall {
 
 
 echo "⚙️  Updating apt packages"
-install || echo "❌ Failed to install apt packages"
+install || echo "❌ Failed to install packages"
 
 echo "⚙️  Removing old packages"
-uninstall || echo "❌ Failed to remove old apt packages"
+uninstall || echo "❌ Failed to remove old packages"
 
 echo "⚙️  Updating batcat cache"
 batcat cache --build || echo "❌ Failed to build batcat cache"
