Clean up install scripts

diff --git a/.chezmoiscripts/run_after_02-atuin b/.chezmoiscripts/run_after_02-atuin
--- a/.chezmoiscripts/run_after_02-atuin
+++ b/.chezmoiscripts/run_after_02-atuin
@@ -2,9 +2,10 @@
 
 NAME='atuin'
 VERSION='18.4.0-beta.1'
+ARCH=$(uname -m)
 
-_LIB="$HOME/.local/lib/atuin"
 _BIN="$HOME/.local/bin/atuin"
+_LIB="$HOME/.local/lib/atuin"
 
 function install {
     if command -v atuin &> /dev/null; then
@@ -14,25 +15,13 @@ function install {
         fi
     fi
 
-    ARCH=$(uname -m)
-    if [ $ARCH != "x86_64" ]; then
-        echo "❌ $ARCH is not supported"
-        return
-    fi
-
-    if [[ -d "$_LIB" ]]; then
-        rm -rf "$_LIB/{*,.*}"
-    else
-        mkdir -p ~/.local/lib/atuin 
-    fi
-    tar -C "$_LIB" --strip-components 1 -xzf <(curl -sL "https://github.com/atuinsh/atuin/releases/download/v$VERSION/atuin-x86_64-unknown-linux-gnu.tar.gz")
-
-    if [[ ! -e "$_BIN" ]]; then
-        ln -s "$_LIB/atuin" "$_BIN"
-    fi
-
+    [[ -e "$_BIN" ]] && rm -rf "$_BIN"
+    [[ -d "$_LIB" ]] && rm -rf "$_LIB/{*,.*}"
+    mkdir -p $_LIB || return 3
+    tar -C "$_LIB" --strip-components 1 -xzf <(curl -sL "https://github.com/atuinsh/atuin/releases/download/v$VERSION/atuin-$ARCH-unknown-linux-gnu.tar.gz") || return 4
+    ln -s "$_LIB/atuin" "$_BIN" || return 5
     echo "✅ $NAME installed successfully"
 }
 
 echo "⚙️  Installing $NAME"
-install || echo "❌ Failed to install $NAME"
+install || echo "❌ Failed to install $NAME: $?"
diff --git a/.chezmoiscripts/run_after_02-entr b/.chezmoiscripts/run_after_02-entr
--- a/.chezmoiscripts/run_after_02-entr
+++ b/.chezmoiscripts/run_after_02-entr
@@ -8,18 +8,18 @@ function install {
         return
     fi
 
-    SUDO=$(get-sudo)
-    TMP="$(mktemp -d)"
-
-    cd $TMP
-    git clone https://github.com/eradman/entr.git
-    cd entr
-    ./configure
-    make test
-    PREFIX=~/.local make install
-    echo "✅ $NAME installed successfully"
+    (
+        TMP="$(mktemp -d)"
+        cd $TMP
+        git clone https://github.com/eradman/entr.git || return 1
+        cd entr
+        ./configure || return 2
+        make testa || return 3
+        PREFIX=~/.local make install || return 4
+        echo "✅ $NAME installed successfully"
+    ) || return $?
 }
 
 echo "⚙️  Installing $NAME"
-install || echo "❌ Failed to install $NAME"
+install || echo "❌ Failed to install $NAME: $?"
 
diff --git a/.chezmoiscripts/run_after_02-fnm b/.chezmoiscripts/run_after_02-fnm
--- a/.chezmoiscripts/run_after_02-fnm
+++ b/.chezmoiscripts/run_after_02-fnm
@@ -8,10 +8,10 @@ function install {
         return
     fi
 
-    curl -fsSL https://fnm.vercel.app/install | bash -s -- -s
-    $XDG_DATA_HOME/fnm/fnm use --install-if-missing 20
+    curl -fsSL https://fnm.vercel.app/install | bash -s -- -s || return 1
+    $XDG_DATA_HOME/fnm/fnm use --install-if-missing 20 --return 2
     echo "✅ $NAME installed successfully"
 }
 
 echo "⚙️  Installing $NAME"
-install || echo "❌ Failed to install $NAME"
+install || echo "❌ Failed to install $NAME: $?"
diff --git a/.chezmoiscripts/run_after_02-fzf b/.chezmoiscripts/run_after_02-fzf
--- a/.chezmoiscripts/run_after_02-fzf
+++ b/.chezmoiscripts/run_after_02-fzf
@@ -1,7 +1,10 @@
 #!/usr/bin/env zsh
 
 NAME="fzf"
-VERSION='0.53.0'
+VERSION='0.54.2'
+ARCH=$(uname -m)
+
+_BIN="$HOME/.local/bin/fzf"
 
 function install {
     if command -v fzf &> /dev/null; then
@@ -11,17 +14,21 @@ function install {
         fi
     fi
 
-    ARCH=$(uname -m)
-    if [ $ARCH != "x86_64" ]; then
+    if [[ $ARCH -eq "x86_64" ]]; then
+        ARCH="amd64"
+    elif [[ $ARCH -eq "arm64" ]]; then
+        ARCH="arm8"
+    else
         echo "❌ $ARCH is not supported"
-        return
+        return 1
     fi
 
-    wget -qO- "https://github.com/junegunn/fzf/releases/download/$VERSION/fzf-$VERSION-linux_amd64.tar.gz" \
-        | tar -xz -C $HOME/.local/bin
-    chmod +x "$HOME/.local/bin/fzf"
+    [[ -e "$_BIN" ]] && rm "$_BIN"
+    wget -qO- "https://github.com/junegunn/fzf/releases/download/v$VERSION/fzf-$VERSION-linux_$ARCH.tar.gz" \
+        | tar -xz -C $HOME/.local/bin || return 2
+    chmod +x "$_BIN" || return 3
     echo "✅ $NAME installed successfully"
 }
 
 echo "⚙️  Installing $NAME"
-install || echo "❌ Failed to install $NAME"
+install || echo "❌ Failed to install $NAME: $?"
diff --git a/.chezmoiscripts/run_after_02-go b/.chezmoiscripts/run_after_02-go
--- a/.chezmoiscripts/run_after_02-go
+++ b/.chezmoiscripts/run_after_02-go
@@ -1,31 +1,34 @@
 #!/usr/bin/env zsh
 
 NAME='go'
-version='go1.22.1'
+VERSION='go1.22.1'
+ARCH=$(uname -m)
+_LIB="$HOME/.local/lib/go"
+_LIB="$HOME/.local/bin/go"
 function install {
     if command -v go &> /dev/null; then
-        if [[ $(go version) =~ $version ]]; then
+        if [[ $(go version) =~ $VERSION ]]; then
             echo "✅ $NAME is up to date"
             return
         fi
     fi
 
-    ARCH=$(uname -m)
-    if [ $ARCH != "x86_64" ]; then
+    if [[ $ARCH -eq "x86_64" ]]; then
+        ARCH="amd64"
+    elif [[ $ARCH -eq "arm64" ]]; then
+        ARCH="arm64"
+    else
         echo "❌ $ARCH is not supported"
-        return
+        return 1
     fi
 
-    mkdir -p ~/.local/lib
-    zsh -c "tar -C ~/.local/lib -xzf <(curl -sL https://go.dev/dl/go1.22.1.linux-amd64.tar.gz)"
-
-    if [[ -L ~/.local/bin/go ]]; then
-        unlink ~/.local/bin/go
-    fi
-
-    ln -s ~/.local/lib/go/bin/go ~/.local/bin/ || true
+    [[ -d "$_LIB" ]] && rm "$_LIB"
+    [[ -e ~/.local/bin/go ]] unlink ~/.local/bin/go
+    mkdir -p "$_LIB" || return 1
+    zsh -c "tar -C ~/.local/lib -xzf <(curl -sL https://go.dev/dl/go1.22.1.linux-amd64.tar.gz)" || return 2
+    ln -s "$_LIB/bin/go" "$_BIN" || return 3
     echo "✅ $NAME installed successfully"
 }
 
 echo "⚙️  Installing $NAME"
-install || echo "❌ Failed to install $NAME"
+install || echo "❌ Failed to install $NAME: $?"
diff --git a/.chezmoiscripts/run_after_02-rustup b/.chezmoiscripts/run_after_02-rustup
--- a/.chezmoiscripts/run_after_02-rustup
+++ b/.chezmoiscripts/run_after_02-rustup
@@ -8,10 +8,10 @@ function install {
         return
     fi
 
-    curl https://sh.rustup.rs -sSf | sh -s -- -y
+    curl https://sh.rustup.rs -sSf | sh -s -- -y || return 1
     echo "✅ $NAME installed successfully"
 }
 
 echo "⚙️  Installing $NAME"
-install || echo "❌ Failed to install $NAME"
+install || echo "❌ Failed to install $NAME: $?"
 
diff --git a/.chezmoiscripts/run_after_02-sdkman b/.chezmoiscripts/run_after_02-sdkman
--- a/.chezmoiscripts/run_after_02-sdkman
+++ b/.chezmoiscripts/run_after_02-sdkman
@@ -1,16 +1,16 @@
-#!/usr/bin/env bash
+#!/usr/bin/env zsh
 
 NAME="SDKMan"
 
 function install {
   if [[ ! -s "$SDKMAN_DIR/bin/sdkman-init.sh" ]]; then
-    source <(curl -s "https://get.sdkman.io?rcupdate=false")
-    source "$SDKMAN_DIR/bin/sdkman-init.sh"
+    source <(curl -s "https://get.sdkman.io?rcupdate=false") || return 1
+    source "$SDKMAN_DIR/bin/sdkman-init.sh" || return 2
   else 
-     echo "✅ $NAME is already installed"
+    echo "✅ $NAME is already installed"
   fi
 }
 
 echo "⚙️  Installing $NAME"
-install || echo "❌ Failed to install $NAME"
+install || echo "❌ Failed to install $NAME: $?"
 
diff --git a/.chezmoiscripts/run_after_02-zoxide b/.chezmoiscripts/run_after_02-zoxide
--- a/.chezmoiscripts/run_after_02-zoxide
+++ b/.chezmoiscripts/run_after_02-zoxide
@@ -7,10 +7,10 @@ function install {
         return
     fi
 
-    curl -sS https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | bash
+    curl -sS https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | bash || return 1
     echo "✅ $NAME installed successfully"
 }
 
 echo "⚙️  Installing $NAME"
-install || echo "❌ Failed to install $NAME"
+install || echo "❌ Failed to install $NAME: $?"
 
