Revamp scripts

diff --git a/.chezmoiscripts/run_after_02-entr b/.chezmoiscripts/run_after_02-entr
--- a/.chezmoiscripts/run_after_02-entr
+++ b/.chezmoiscripts/run_after_02-entr
@@ -1,10 +1,10 @@
 #!/usr/bin/env zsh
 
-source "$JLIB" 
+NAME="Entr"
 
 function install {
     if command -v entr &> /dev/null; then
-        echo "Entr is already installed"
+        echo "✅ $NAME is already installed"
         return
     fi
 
@@ -17,7 +17,9 @@ function install {
     ./configure
     make test
     PREFIX=~/.local make install
+    echo "✅ $NAME installed successfully"
 }
 
-install || echo Failed to install Entr
+echo "⚙️  Installing $NAME"
+install || echo "❌ Failed to install $NAME"
 
diff --git a/.chezmoiscripts/run_after_02-fnm b/.chezmoiscripts/run_after_02-fnm
--- a/.chezmoiscripts/run_after_02-fnm
+++ b/.chezmoiscripts/run_after_02-fnm
@@ -1,13 +1,17 @@
 #!/usr/bin/env zsh
 
+NAME="fnm"
+
 function install {
     if command -v fnm &> /dev/null; then
-        echo "fnm is already installed"
+        echo "✅ $NAME is already installed"
         return
     fi
 
     curl -fsSL https://fnm.vercel.app/install | bash -s -- -s
     $XDG_DATA_HOME/fnm/fnm use --install-if-missing 20
+    echo "✅ $NAME installed successfully"
 }
 
-install || echo Failed to install fnm
+echo "⚙️  Installing $NAME"
+install || echo "❌ Failed to install $NAME"
diff --git a/.chezmoiscripts/run_after_02-fzf b/.chezmoiscripts/run_after_02-fzf
--- a/.chezmoiscripts/run_after_02-fzf
+++ b/.chezmoiscripts/run_after_02-fzf
@@ -1,25 +1,27 @@
 #!/usr/bin/env zsh
 
+NAME="fzf"
 VERSION='0.53.0'
 
 function install {
     if command -v fzf &> /dev/null; then
-        if [[ $(go version) =~ $VERSION ]]; then
-            echo "fzf is up to date"
+        if [[ $(fzf --version) =~ $VERSION ]]; then
+            echo "✅ $NAME is up to date"
             return
         fi
     fi
 
     ARCH=$(uname -m)
     if [ $ARCH != "x86_64" ]; then
-        echo "$ARCH is not supported"
+        echo "❌ $ARCH is not supported"
         return
     fi
 
     wget -qO- "https://github.com/junegunn/fzf/releases/download/$VERSION/fzf-$VERSION-linux_amd64.tar.gz" \
         | tar -xz -C $HOME/.local/bin
     chmod +x "$HOME/.local/bin/fzf"
+    echo "✅ $NAME installed successfully"
 }
 
-
-install || echo "Failed to install fzf"
+echo "⚙️  Installing $NAME"
+install || echo "❌ Failed to install $NAME"
diff --git a/.chezmoiscripts/run_after_02-go b/.chezmoiscripts/run_after_02-go
--- a/.chezmoiscripts/run_after_02-go
+++ b/.chezmoiscripts/run_after_02-go
@@ -4,20 +4,22 @@ version='go1.22.1'
 function install {
     if command -v go &> /dev/null; then
         if [[ $(go version) =~ $version ]]; then
-            echo "Go is up to date"
+            echo "✅ $NAME is up to date"
             return
         fi
     fi
 
     ARCH=$(uname -m)
     if [ $ARCH != "x86_64" ]; then
-        echo "$ARCH is not supported"
+        echo "❌ $ARCH is not supported"
         return
     fi
 
     mkdir -p ~/.local/lib
     zsh -c "tar -C ~/.local/lib -xzf <(curl -sL https://go.dev/dl/go1.22.1.linux-amd64.tar.gz)"
     ln -s ~/.local/lib/go/bin/go ~/.local/bin/ || true
+    echo "✅ $NAME installed successfully"
 }
 
-install || echo Failed to install Go
+echo "⚙️  Installing $NAME"
+install || echo "❌ Failed to install $NAME"
diff --git a/.chezmoiscripts/run_after_02-nvim b/.chezmoiscripts/run_after_02-nvim
--- a/.chezmoiscripts/run_after_02-nvim
+++ b/.chezmoiscripts/run_after_02-nvim
@@ -1,8 +1,9 @@
 #!/usr/bin/env zsh
 
+NAME="Neovim"
 function install {
     if command -v nvim &> /dev/null; then
-        echo "nvim is already installed"
+        echo "✅ $NAME is already installed"
         return
     fi
 
@@ -10,7 +11,7 @@ function install {
         SUDO=""
     else
         if ! command -v sudo &> /dev/null; then
-            echo "Error: sudo is not installed. Please install sudo or run as root."
+            echo "❌ sudo is not installed. Please install sudo or run as root."
             exit 1
         fi
         SUDO="sudo"
@@ -19,7 +20,9 @@ function install {
     $SUDO add-apt-repository -y ppa:neovim-ppa/unstable
     $SUDO apt-get update
     $SUDO apt-get install -y neovim ripgrep fd-find
+    echo "✅ $NAME installed successfully"
 }
 
-install || echo Failed to install nvim
+echo "⚙️  Installing $NAME"
+install || echo "❌ Failed to install $NAME"
 
diff --git a/.chezmoiscripts/run_after_02-sdkman b/.chezmoiscripts/run_after_02-sdkman
--- a/.chezmoiscripts/run_after_02-sdkman
+++ b/.chezmoiscripts/run_after_02-sdkman
@@ -1,13 +1,16 @@
 #!/usr/bin/env bash
 
+NAME="SDKMan"
+
 function install {
   if [[ ! -s "$SDKMAN_DIR/bin/sdkman-init.sh" ]]; then
     source <(curl -s "https://get.sdkman.io?rcupdate=false")
     source "$SDKMAN_DIR/bin/sdkman-init.sh"
   else 
-    echo SDKman already installed
+     echo "✅ $NAME is already installed"
   fi
 }
 
-install || echo Failed to install SDKman
+echo "⚙️  Installing $NAME"
+install || echo "❌ Failed to install $NAME"
 
diff --git a/.chezmoiscripts/run_after_02-zoxide b/.chezmoiscripts/run_after_02-zoxide
--- a/.chezmoiscripts/run_after_02-zoxide
+++ b/.chezmoiscripts/run_after_02-zoxide
@@ -1,13 +1,16 @@
 #!/usr/bin/env zsh
 
+NAME="Zoxide"
 function install {
     if command -v zoxide &> /dev/null; then
-        echo "Zoxide is already installed"
+        echo "✅ $NAME is already installed"
         return
     fi
 
     curl -sS https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | bash
+    echo "✅ $NAME installed successfully"
 }
 
-install || echo Failed to install Zoxide
+echo "⚙️  Installing $NAME"
+install || echo "❌ Failed to install $NAME"
 
